### ISSUE TITLE
Main actors and team image is Denglish (Dutch-English)

### ISSUE THREAD

**Issue by jmbguardian360io** [G360DAO/community#28]

**Comment by jmbguardian360io** [comment]
![Image](https://user-images.githubusercontent.com/101091185/195858700-8d9f2b47-5fab-4be4-a59f-bc2cc9a2ff59.png)

**Comment by jmbguardian360io** [comment]
@olivier1977 can you please fix this one?

**Comment by olivier1977** [comment]
done

**Comment by olivier1977** [comment]
![image](https://user-images.githubusercontent.com/24956161/203275647-bb0d7161-26ac-462f-9240-3609b907e170.png)

nog een update naar aanleiding van de client bucket ;-)

**Comment by jmbguardian360io** [comment]
The whitepaper has been updated as well
